### ISSUE TITLE
Build issues with below code 

### ISSUE THREAD

**Issue by chandra-ch** [XperiaOS/platform_frameworks_base#1]
frameworks/base/services/core/java/com/android/server/am/ActivityManagerService.java:5947: error: package LaunchTimeTracker does not exist
            final LaunchTimeTracker.Entry entry = mStackSupervisor
                                   ^
frameworks/base/services/core/java/com/android/server/am/ActivityManagerService.java:5948: error: cannot find symbol
                    .getLaunchTimeTracker().getEntry(mStackSupervisor.getWindowingMode());
                    ^
  symbol:   method getLaunchTimeTracker()
  location: variable mStackSupervisor of type ActivityStackSupervisor
2 errors

        // Hack for pi
        // When an app process is removed, activities from the process may be relaunched. In the
        // case of forceStopPackageLocked the activities are finished before any window is drawn,
        // and the launch time is not cleared. This will be incorrectly used to calculate launch
        // time for the next launched activity launched in the same windowing mode.
        if (clearLaunchStartTime) {
            final LaunchTimeTracker.Entry entry = mStackSupervisor
                    .getLaunchTimeTracker().getEntry(mStackSupervisor.getWindowingMode());
            if (entry != null) {
                entry.mLaunchStartTime = 0;
            }
        }

**Comment by Thespartann** [comment]
Issue been fixed.
