### ISSUE TITLE
build issues 2

### ISSUE THREAD

**Issue by chandra-ch** [XperiaOS/platform_frameworks_base#2]
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/HotspotControllerImpl.java:112: error: cannot find symbol
        mWifiStateReceiver.setListening(shouldListen);
        ^
  symbol:   variable mWifiStateReceiver
  location: class HotspotControllerImpl
1 error

**Comment by Thespartann** [comment]
Issue been fixed.
